import {
  Users,
  Mountain,
  Waves,
  Moon,
  Car,
  TentTree,
  Flame,
  Ship,
  GlassWater,
  TreePine,
  Fish,
  Route,
  PlaneTakeoff,
  MapPin,
  Sun,
  Camera,
  CarFront,
  Map as MapIcon,
  CalendarDays,
  MapPinned,
  Wallet,
  Backpack,
  Phone,
  Hospital,
  TriangleAlert,
  CloudRain,
  Wind,
  Thermometer,
  Navigation,
  ExternalLink,
  ChevronDown,
  Info,
  Ticket,
  Clock,
  Sparkles,
  ShieldAlert,
  CircleHelp,
  Utensils,
  Anchor,
} from 'lucide-react'

const iconMap = {
  users: Users,
  mountain: Mountain,
  waves: Waves,
  moon: Moon,
  car: Car,
  tent: TentTree,
  flame: Flame,
  ship: Ship,
  'glass-water': GlassWater,
  'tree-pine': TreePine,
  fish: Fish,
  route: Route,
  'plane-takeoff': PlaneTakeoff,
  'map-pin': MapPin,
  sun: Sun,
  camera: Camera,
  'car-front': CarFront,
  map: MapIcon,
  calendar: CalendarDays,
  'map-pinned': MapPinned,
  wallet: Wallet,
  backpack: Backpack,
  phone: Phone,
  hospital: Hospital,
  warn: TriangleAlert,
  rain: CloudRain,
  wind: Wind,
  thermometer: Thermometer,
  navigation: Navigation,
  external: ExternalLink,
  chevron: ChevronDown,
  info: Info,
  ticket: Ticket,
  clock: Clock,
  sparkles: Sparkles,
  shield: ShieldAlert,
  utensils: Utensils,
  anchor: Anchor,
}

export type IconName = keyof typeof iconMap

export interface IconProps {
  name: IconName
  className?: string
}

export function Icon({ name, className }: IconProps) {
  const Cmp = iconMap[name] ?? CircleHelp
  return <Cmp className={className} aria-hidden="true" />
}
